import { chromium } from "playwright";
const b = await chromium.launch();
const ctx = await b.newContext({ viewport:{width:1440,height:900}, deviceScaleFactor:2 });
const p = await ctx.newPage();
const errs=[], failed=[];
p.on("pageerror",e=>errs.push(String(e)));
p.on("response", r => { if (r.status() >= 400 && r.url().includes("furniture")) failed.push(r.status()+" "+r.url().split("/").pop()); });
await p.addInitScript(()=>{try{sessionStorage.setItem("alma:intro-seen","1");localStorage.setItem("alma:hero","editorial");}catch{}});
await p.goto("http://localhost:3000/en",{waitUntil:"networkidle"});
await new Promise(r=>setTimeout(r,2500));
const imgs = await p.evaluate(()=>[...document.images].filter(i=>i.currentSrc.includes("furniture")||i.currentSrc.includes("unsplash")).map(i=>({src:decodeURIComponent(i.currentSrc).split("furniture%2F").pop().split("furniture/").pop().split("&")[0].slice(0,52), ok:i.complete&&i.naturalWidth>0})));
await p.screenshot({path:"scripts/shots/real-hero.png"});
await p.evaluate(()=>{window.dispatchEvent(new CustomEvent("alma:scroll-lock"));const el=document.querySelector("#projects");window.scrollTo(0,el.getBoundingClientRect().top+window.scrollY-200);});
await new Promise(r=>setTimeout(r,2600));
await p.screenshot({path:"scripts/shots/real-projects.png"});
await p.evaluate(()=>{const el=document.querySelector("#transformation");window.scrollTo(0,el.getBoundingClientRect().top+window.scrollY-100);});
await new Promise(r=>setTimeout(r,2200));
await p.screenshot({path:"scripts/shots/real-beforeafter.png"});
const unsplash = await p.evaluate(()=>[...document.images].filter(i=>i.src.includes("unsplash")).length);
console.log("images loaded:", imgs.filter(i=>i.ok).length, "broken:", imgs.filter(i=>!i.ok).length, "unsplash remaining:", unsplash);
console.log("http failures:", failed.length ? failed.join(" | ") : "none");
console.log(errs.length?("PAGE ERRORS: "+errs[0].slice(0,120)):"no page errors");
await b.close();
